//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom.presentation.website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment_status
    {
        public Appointment_status()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public short ID { get; set; }
        public string NameEN { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ICollection<Appointment> Appointments { get; set; }
    }
}
