//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom.presentation.website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int ID { get; set; }
        public int ScheduleID { get; set; }
        public string PatientName { get; set; }
        public string ContactNumber { get; set; }
        public System.DateTime Date { get; set; }
        public System.TimeSpan SlotTime { get; set; }
        public short StatusID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Appointment_status Appointment_status { get; set; }
        public virtual DoctorSchedule DoctorSchedule { get; set; }
    }
}
