//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom.presentation.website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.CityLocations = new HashSet<CityLocation>();
            this.Doctors = new HashSet<Doctor>();
            this.Hospitals = new HashSet<Hospital>();
        }
    
        public int ID { get; set; }
        public string NameEN { get; set; }
        public int CountryID { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Country Country { get; set; }
        public virtual ICollection<CityLocation> CityLocations { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<Hospital> Hospitals { get; set; }
    }
}
