//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom.presentation.website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Doctor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Doctor()
        {
            this.DoctorReviews = new HashSet<DoctorReview>();
            this.DoctorSchedules = new HashSet<DoctorSchedule>();
            this.DoctorUserLikes = new HashSet<DoctorUserLike>();
        }
    
        public int ID { get; set; }
        public string NameEN { get; set; }
        public string Qualification { get; set; }
        public Nullable<decimal> Fee { get; set; }
        public int SpecialityID { get; set; }
        public bool IsActive { get; set; }
        public int ReviewCount { get; set; }
        public int LikeCount { get; set; }
        public Nullable<System.DateTime> ExperienceFrom { get; set; }
        public int HospitalID { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public string ImageExt { get; set; }
        public string Description { get; set; }
    
        public virtual Department Department { get; set; }
        public virtual Hospital Hospital { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorReview> DoctorReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorSchedule> DoctorSchedules { get; set; }
        public virtual Specialization Specialization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoctorUserLike> DoctorUserLikes { get; set; }
    }
}
