//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ecom.presentation.website.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hospital
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hospital()
        {
            this.Doctors = new HashSet<Doctor>();
            this.HospitalInsurances = new HashSet<HospitalInsurance>();
            this.HospitalReviews = new HashSet<HospitalReview>();
            this.HospitalUserLikes = new HashSet<HospitalUserLike>();
            this.HospitalAdmins = new HashSet<HospitalAdmin>();
        }
    
        public int ID { get; set; }
        public string NameEN { get; set; }
        public string Address { get; set; }
        public string ContactNumber { get; set; }
        public string SecondNumber { get; set; }
        public Nullable<int> CityLocationID { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public bool IsActive { get; set; }
        public int LikeCount { get; set; }
        public int ReviewCount { get; set; }
        public bool IsOpenAlways { get; set; }
    
        public virtual CityLocation CityLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Doctor> Doctors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalInsurance> HospitalInsurances { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalReview> HospitalReviews { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalUserLike> HospitalUserLikes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HospitalAdmin> HospitalAdmins { get; set; }
    }
}
